use_frameworks!

target 'LeetcodeSwiftUtils_Example' do
  pod 'LeetcodeSwiftUtils', :path => '../'

  target 'LeetcodeSwiftUtils_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.2.0'
    pod 'Nimble', '~> 7.0'
  end
end
